### ISSUE TITLE
Review Design Wireframe: Terms & Conditions page

### ISSUE THREAD

**Issue by lem31** [NoroffFEU/musikkforandrerliv.no#104]
- [x] Visual Hierarchy
- [x] Layout
- [x] Consistency
- [x] Screen size
- [x] Usability Principles
- [x] Web Content Accessibility Guidelines (WCAG)
- [x] Colors
- [x] Fonts
- [x] Whitespace and padding
- [x] Image quality
- [x] Iconography
- [x] Micro interactions
- [x] Error states and feedback
- [x] Performance Optimization
- [x] Design documentation

See Design wireframe/prototype checklist for more info

**Comment by Whisperpiano** [comment]
**Desktop**

- Header: The arrow in "About Us" and "More" have different space between, would be better if they have the same distance.
- Subscribe to newsletter: You could enhance it by adding something that distinguishes this section from the rest of the page. This makes it easier to differentiate what the terms are and what the newsletter is.
- Footer: The middle section is not centered properly.

**Mobile**

- Font size: The font size is not scalable, and both have 32px. On desktop, this looks fine, but on mobile, it looks too large.
- Covering law: is the only element with the text not centered, that makes a bit weird the consistency of the page. 
- Newsletter: same as before, add some element to distinguish from the terms.
- Footer: The logo and "Follow Us" has very little padding on the top 

PD: **nice work :)**

**Comment by Vickabu** [comment]
Arrows is connected to "more" not "about us" its to indicate a drope down if more content is added. 

*Since footer and nav is mention i several issues, but with different comments - it needs to be one issue with one precise description. Same with the newsletter. *
