### ISSUE TITLE
Implement Responsiveness - Footer

### ISSUE THREAD

**Issue by benjaminskarding** [NoroffFEU/musikkforandrerliv.no#152]
Implement responsiveness on the footer using Tailwind CSS. 

Check docs for info: https://tailwindcss.com/docs/responsive-design
Will be helpful to check external resources for input and information also here. (Youtube or similar)

For reference styling the footer go to: https://www.figma.com/design/e7uE5Lf9XhFvMhXaFOSZxq/Design-File---MMF?node-id=0-1&t=pGagvn6EOPz75AJw-0

The design the client wants to go forward with is called HiFi. 

- [ ] Checked by QA

**Comment by Arkuradev** [comment]
Please create a branch for this task before doing any actual development on this task. Otherwise nothing will be pushed back to the main when this task has been solved.
