### ISSUE TITLE
Review Design Wireframe: Children specific article 

### ISSUE THREAD

**Issue by lem31** [NoroffFEU/musikkforandrerliv.no#236]

**Comment by lem31** [comment]
- [ ] Visual Hierarchy
- [ ] Layout
- [ ] Consistency
- [ ] Screen size
- [ ] Usability Principles
- [ ] Web Content Accessibility Guidelines (WCAG)
- [ ] Colors
- [ ] Fonts
- [ ] Whitespace and padding
- [ ] Image quality
- [ ] Iconography
- [ ] Micro interactions
- [ ] Error states and feedback
- [ ] Browser compatibility
- [ ] Performance Optimization
- [ ] Design documentation

See Design wireframe/prototype checklist for more info

**Comment by EliNygard** [comment]
- The heading is a bit difficult to read. Not difficult, but uncomfortable. Maybe consider using uppercase or add letter spacing.  
- heading (h2?) over the paragraphs. Font used: Just another hand. Why not use Montserrat as on other pages when it is not a h1?
- Subscribe to our newsletter: Why is there a paragraph with text content on mobile view and not on desktop view? And why is the button inside the border on desktop view and not on mobile view?

**Comment by EliNygard** [comment]
Review finished and comments added for Design Team

**Comment by Vickabu** [comment]
This page has been scraped by the client.

**Comment by EliNygard** [comment]
Aha, thank you. Closing this then.
