### ISSUE TITLE
Review Design Wireframe: Overall consistency: Typography

### ISSUE THREAD

**Issue by lem31** [NoroffFEU/musikkforandrerliv.no#238]
Review typography consistency across all pages

**Comment by Kittypoda** [comment]
- The typography does not match the style guide. The style guide specifies that H1 should use the Montserrat font, but in the design, only the "Just Another Hand" font is being used. The design team needs to either update the H1 font in the design to match the style guide (using Montserrat) or update the style guide to reflect the font currently used (Just Another Hand).

This issue also occurs with other headings throughout the design. Please ensure that all headings in the design adhere to the guidelines specified in the style guide.

- There are inconsistent letter spacings used in the heading 1 throughout the page. Some H1 headings have a letter spacing of 5% (which is more readable), while in other places, the letter spacing is 0%. Please ensure that the typography aligns with the guidelines specified in the style guide for consistent letter spacing across all headings.

- There are also inconsistencies in the body text regarding line height and letter spacing. Please ensure that the typography aligns with the guidelines specified in the style guide for consistent line height and letter spacing throughout the body text.

**Comment by Vickabu** [comment]
The comment on H1 is allready answerd in other issues, and has always been uunder alternativ font - and description of its use under Typography Guidelines. But we have as mention earlyer updated the Heading section as well.

Spacing is also beeing worked on, and are mentioned in other issues. We will update there so it is not a lot of issues on the same thing.
