### ISSUE TITLE
Review Design Wireframe: Overall consistency: Icons & Buttons

### ISSUE THREAD

**Issue by lem31** [NoroffFEU/musikkforandrerliv.no#239]
Review Icon & Button consistency across all pages

**Comment by Kittypoda** [comment]
Overall, the consistency with the buttons and icons is good. However, I do have some suggestions for improvement:

- Mobile screen: The "Subscribe to newsletter" button is placed inside the email text field. It might be better to position it outside the text field, similar to the desktop wireframes.

- Our work page: The green buttons at the top of the page are a bit confusing as I don't see them in any other wireframe in Figma. This inconsistency makes the design appear less cohesive.

- The red buttons that appear on every desktop page have a contrast ratio that may not meet WCAG standards. 

The font size used on these buttons is 20px. According to WCAG guidelines, for text or images of text that are larger than 18pt (which roughly translates to 24px) or 14pt (which roughly translates to 18.67px) if bold, the minimum contrast ratio required is 3:1 for text against its background.

<img width="141" alt="Skjermbilde 2024-04-05 kl  09 00 59" src="https://github.com/NoroffFEU/musikkforandrerliv.no/assets/146728692/c93658c3-98d9-42d9-a82a-9eb1e465674f">
<img width="734" alt="Skjermbilde 2024-04-05 kl  09 19 35" src="https://github.com/NoroffFEU/musikkforandrerliv.no/assets/146728692/4a15705d-bdb9-4dd7-ba06-2bc790e6c957">

**Comment by Vickabu** [comment]
We allready have issues that mention all of this, and changes has been made but are not done.
