### ISSUE TITLE
Review Design Wireframe: Overall consistency: Spacing

### ISSUE THREAD

**Issue by lem31** [NoroffFEU/musikkforandrerliv.no#240]
Review spacing consistency across all pages

**Comment by EliNygard** [comment]
There are spacing conflicts across many pages. I can not see that the designers have created a grid. This makes it difficult to place items accordingly. One example: one heading has less spacing to the header than another heading on another page.  Look at the Support us page. One two mobile pages the heading overlap the red box. The spacing of the elements "Volunteer, Donation, Fundraising" are very big on mobile view. The team needs to create a grid to make sure spacing is consistent. We can not review it as it is now, and the developers needs the consistency to know how much padding and margin they shall add.

**Comment by Vickabu** [comment]
This is allready being worked on as it is mentioned in more issues. The grid that is mentioned her is no longer in use, and we are working on layot after grid.

Footer is allready changed.

**Comment by EliNygard** [comment]
Great! Thank you. Looking forward to see the new grid. Then I'll close this issue.
