### ISSUE TITLE
Create HTML and Style - Section 1 - Privacy Policy page

### ISSUE THREAD

**Issue by Iseost** [NoroffFEU/musikkforandrerliv.no#466]
![Image](https://github.com/NoroffFEU/musikkforandrerliv.no/assets/142426482/901fa37a-0b47-45cf-9155-e170b32d5184)

Check status on this task first. Compare it to the figma design. 

- [x] Status checked and compared to figma design. 
- [x] Finish the HTML and style elements for the privacy policy page. 
- [x] Hand over to QA for review when finished. 

- [ ] Checked by QA

**Comment by Arkuradev** [comment]
How is this task coming along?
