### ISSUE TITLE
Update Colors - tailwind.config.js file

### ISSUE THREAD

**Issue by Iseost** [NoroffFEU/musikkforandrerliv.no#470]
New colors:
- light-green #B2CAC2

- light-red #F1DBD3

Remove: 
- sky-blue
- frost-blue

---
![Image](https://github.com/NoroffFEU/musikkforandrerliv.no/assets/142426482/4ebcd8eb-1676-44bf-a6c3-0498fe58cfc5)
![Image](https://github.com/NoroffFEU/musikkforandrerliv.no/assets/142426482/acb88e7c-058c-4366-83a2-85e8c75a9bf7)
![Image](https://github.com/NoroffFEU/musikkforandrerliv.no/assets/142426482/0a842d2e-b1b1-493b-8557-2dddcf9789a4)
![Image](https://github.com/NoroffFEU/musikkforandrerliv.no/assets/142426482/ca7e942f-1752-48e6-b3a5-5735d9936025)

**Comment by cnnrbrn** [comment]
Assign one dev to check if this still needs to be done.
