### ISSUE TITLE
FIGMA: New colour palette

### ISSUE THREAD

**Issue by senbet22** [NoroffFEU/musikkforandrerliv.no#523]
We need a new and more colourful colour palette. Use the figma file to see the old colour palette. Edit the colour palette as needed and save the changes. After that replace the new colours in the code and update the files. If needed write the colors in the root of the css. 

The colour palette need to include:
- [x] Colours that resemble the pictures and the t-shirts the kids have been given. Plus if its some resemblance of the traditional culture in madagascar.
- [x] More eye catching colours.
- [x] Create/find new brand colours.

Suggested Progression:
- [x] Do some research on the school, the image gallery we have access to on google disk, the madagascar culture
- [x] Go the figma file and look at the existing colour palette
- [x] Experiment with new colours and find some bright colours that can lift the page and make it more colourful
- [x] Edit the new colours into the figmafile
- [ ] Implement the new colours into the code 
- [ ] Save and update the code

**Comment by senbet22** [comment]
Issue: The yellow in red background while in hover effect does not meet the contrast standards.



![Image](https://github.com/NoroffFEU/musikkforandrerliv.no/assets/152603405/4b046743-5ff9-48c4-a030-3b81a9e90781)
![Image](https://github.com/NoroffFEU/musikkforandrerliv.no/assets/152603405/b7f90945-2dee-4c7d-875d-953215d9e7c1)

**Comment by idatold** [comment]
I fixed this issue (it was part of the old design, and I did not see that it changed color )

 It says what to do in the buttons task, but the idea for the buttons on the page is that they will go a bitt bigger when hovering over them so that they get modernized as well :)

**Comment by senbet22** [comment]
Great! will send it forward to Dev team then. :)
