### ISSUE TITLE
Configure Decap CMS

### ISSUE THREAD

**Issue by cnnrbrn** [NoroffFEU/musikkforandrerliv.no#533]
The CMS to be used for the site is Decap, formerly Netlify CMS. (link to the docs)
 
With Decap the content is stored as markdown files within the same repo as the code.
 
Decap provides a user interface (UI) for the CMS to add/edit and delete the markdown files, but this requires authentication so initially we will manually edit the markdown files. Later we will configure auth so that the client can edit through the UI.
 
This task requires:
 
- investigating how to configure the repo to use Decap. There is an existing PR that contains a config file. Can we use that? Does it match the required content structure?
- investigating how multiple languages are handled. Are they separate markdown files? JSON?
- once the repo is configured, how do we run it on localhost?

**Comment by cnnrbrn** [comment]
@slerbakk @danielekeberg @danielekeberg Any progress on this?

**Comment by danielekeberg** [comment]
@cnnrbrn I've created a PR about this task.
Setup config.yml & cms/admin/index.html

**Comment by cnnrbrn** [comment]
Once QA checks that the config matches the required content structure we can merge this PR.

We do need to split these into different tasks then:

- investigating how multiple languages are handled. Are they separate markdown files? JSON?
- once the repo is configured, how do we run it on localhost?
