### ISSUE TITLE
Create Favicon

### ISSUE THREAD

**Issue by Arkuradev** [NoroffFEU/musikkforandrerliv.no#559]
This task should be started after the logo has been confirmed after the design team has met with the client and the logo has been decided. Meeting is set to 12.00 on September 20th. 

You will be informed about the result of the meeting.

The favicon will be based of the selected logo. 

- [x] Create the favicon using https://favicon.io/
- [x] Implement the favicon to the page
- [x] Check that the favicon works on Chrome, Firefox, Edge and Safari. 

- [x] Checked by QA

**Comment by Arkuradev** [comment]
There will be a slight delay with creating the favicon until client has decided upon their logo design for the site.

**Comment by ankiiin** [comment]
The client wants to use the original logo.

**Comment by Andlie94** [comment]
sent to qa for check

**Comment by Andlie94** [comment]
done
