### ISSUE TITLE
Integrate the loading indicators

### ISSUE THREAD

**Issue by T0nj3** [NoroffFEU/musikkforandrerliv.no#569]
From design-team (code at the bottom):
> Hello!
> 
> 
> 
> I've looked at the different places for the indicators and have developed these suggestions. Essentially we will be using a soft round animated loader to fit the caring message we want to portray to the user. Here it is applied to the different places on the page.
> 
> 
> 
> Newsletter button:
> 
> ![image](https://github.com/user-attachments/assets/576a3efc-8ad0-499f-8f1f-f9853e79d376)
> 
> 
> 
> Contact form and contact information:
> 
> ![image](https://github.com/user-attachments/assets/a7fe6c26-305d-4cfd-88ee-e2ddc3ddae36)
> 
> ![image](https://github.com/user-attachments/assets/625e8765-0652-45f2-b9c7-429ea7d101d7)
> 
> 
> 
> I haven't seen any design for the search bar so I made a quick suggestion on this, but if that is not within the scope of this project then the loading indicator I think should be applied the same:
> 
> ![image](https://github.com/user-attachments/assets/5396e490-08fc-4fe1-b4f4-9a6166d3b7a6)
> 
> 
> 
> Further, we are going to be having a meeting discussing the Support Us page, so a loading indicator after a donation might not be necessary anymore, but if it were to be needed again here is how I imagine it being applied:
> 
> ![image](https://github.com/user-attachments/assets/4c28a1ea-f1a1-40b6-9b04-44da733ed90d)
> 
> 
> 
> The code I found for the loader looked like this:
> 
> HTML:
> 
> `<span class="loader"></span>`
> 
> 
> 
> CSS:
> 
> `.loader {
> 
>   width: 48px;
> 
>   height: 48px;
> 
>   display: inline-block;
> 
>   position: relative;
> 
> }
> 
> .loader::after,
> 
> .loader::before {
> 
>   content: '';  
> 
>   box-sizing: border-box;
> 
>   width: 48px;
> 
>   height: 48px;
> 
>   border-radius: 50%;
> 
>   background: #FFF;
> 
>   position: absolute;
> 
>   left: 0;
> 
>   top: 0;
> 
>   animation: animloader 2s linear infinite;
> 
> }
> 
> .loader::after {
> 
>   animation-delay: 1s;
> 
> }
> 
> 
> 
> @keyframes animloader {
> 
>   0% {
> 
>     transform: scale(0);
> 
>     opacity: 1;
> 
>   }
> 
>   100% {
> 
>     transform: scale(1);
> 
>     opacity: 0;
> 
>   }
> 
> }
> 
>     ` 

 _Originally posted by @nicolaibye in [#567](https://github.com/NoroffFEU/musikkforandrerliv.no/issues/567#issuecomment-2374408172)_

**Comment by cgrotteland92** [comment]
Hopefully what I did is OK, I put the JavaScript in general.mjs. Hope I did not make a mess of things. Maybe someone can check it out before I go any further.
