### ISSUE TITLE
Adjust Gallery Margins in index

### ISSUE THREAD

**Issue by T0nj3** [NoroffFEU/musikkforandrerliv.no#594]
- [x] The gallery looks great, but there is too much margin on the left and right sides. Update the HTML and CSS to reduce the excess margin on both sides.

- [x] Ensure the gallery maintains a balanced layout and looks good across all screen sizes.

![Image](https://github.com/user-attachments/assets/37ef3a0e-f63c-4997-85dc-00a423d7a6f5)

**Comment by cgrotteland92** [comment]
In the Figma design there is no mint green background, should I remove it from the html or just leave it?
