### ISSUE TITLE
Fix Fonts and Colors in "Events" in index

### ISSUE THREAD

**Issue by T0nj3** [NoroffFEU/musikkforandrerliv.no#595]
- [x] Update the fonts for the headings (H1 and H2) in the "Upcoming Events" section to match the design.

- [x] Correct the colors on the dates under "Upcoming Events" to align with the design specifications.

- [x] Ensure consistency across the section, with the correct typography and color scheme.

![Image](https://github.com/user-attachments/assets/25eaced7-e16d-43fc-959e-9c9f490b1a7b)

**Comment by T0nj3** [comment]
Any progress on this? :)

**Comment by EVeskje** [comment]
> Any progress on this? :)

Yes, its done :)
