### ISSUE TITLE
Update Fonts in "Read More" Section "gallery" page

### ISSUE THREAD

**Issue by T0nj3** [NoroffFEU/musikkforandrerliv.no#603]
- [x] Change the font for the H2 headings in the "Read More" section to Montserrat.

- [x] Update the font for the buttons to Montserrat as well.

![Image](https://github.com/user-attachments/assets/9f473795-7746-4967-bfe1-bfdb40bf38d3)

**Comment by nicolaibye** [comment]
Adjusted the font-normal to font-sans on the h2 and buttons for Montserrat. The width and height using padding p-3 and px-8. I also adjusted the text size to text-2xl.
![image](https://github.com/user-attachments/assets/389c60b3-2cfa-4789-9937-92adc7592793)
