### ISSUE TITLE
Fix the pathnames in news page

### ISSUE THREAD

**Issue by T0nj3** [NoroffFEU/musikkforandrerliv.no#635]
- [ ] Fix the pathname for the images in news.html (there is more images than the screenshots that needs attention) 

![Image](https://github.com/user-attachments/assets/cbb6a447-9575-475a-9395-9e57894d10ac)

**Comment by cgrotteland92** [comment]
Hi! From what I can see the pictures on news.html seems fine? They show up on my screen at least.

**Comment by T0nj3** [comment]
Hi! From the live server they are visible. But not the live site! https://norofffeu.github.io/musikkforandrerliv.no/pages/news.html
